# Site settings
title: Konami-JS
email: info@snaptortoise.com
description: > # The original JavaScript easter-egg script.
baseurl: "/konami-js/" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
